-- ============================================================
--  001_account_plan.sql
--  Plan General Contable (SPEC-001): tabla account_plan multi-tenant,
--  índices, búsqueda trigram y triggers de estructura, apuntabilidad
--  y protección (plan.md raíz §2 y §5.a-§5.c). Idempotente.
--
--  Dependencia: requiere `companies` (004_iam.sql) por la FK de tenancy.
--  El runner (src/db/migrate.py) aplica 004 antes que 001 por ese motivo.
--
--  Desviación documentada del plan raíz: se omite
--  `uq_account_plan_tenant_name` porque los nombres del PGC se repiten
--  entre niveles (p. ej. "Proveedores" en 40 y 400, "Clientes" en 43 y
--  430, "Caja" en 58 y 570) y el seed de 002_seed_pgc.sql fallaría.
-- ============================================================

CREATE TABLE IF NOT EXISTS account_plan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL,
    code          VARCHAR(8)   NOT NULL,
    name          VARCHAR(200) NOT NULL,
    parent_id     BIGINT,
    level         SMALLINT     NOT NULL CHECK (level BETWEEN 1 AND 5),
    is_selectable BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_account_plan_tenant_id   UNIQUE (tenant_id, id),
    CONSTRAINT uq_account_plan_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT fk_account_plan_tenant FOREIGN KEY (tenant_id)
        REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_account_plan_parent FOREIGN KEY (tenant_id, parent_id)
        REFERENCES account_plan (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS ix_account_plan_tenant
    ON account_plan (tenant_id);
CREATE INDEX IF NOT EXISTS ix_account_plan_tenant_parent
    ON account_plan (tenant_id, parent_id);
CREATE INDEX IF NOT EXISTS ix_account_plan_tenant_level
    ON account_plan (tenant_id, level, is_selectable);
CREATE INDEX IF NOT EXISTS ix_account_plan_tenant_code
    ON account_plan (tenant_id, code);
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS ix_account_plan_name_trgm
    ON account_plan USING gin (name gin_trgm_ops);

-- §5.a Reglas de estructura del plan
CREATE OR REPLACE FUNCTION chk_account_plan_structure() RETURNS trigger AS $$
DECLARE
    p_count INT;
BEGIN
    IF NEW.code !~ '^[0-9]+$' THEN
        RAISE EXCEPTION 'account_plan: código debe ser numérico (%/%)', NEW.tenant_id, NEW.code;
    END IF;
    IF (NEW.level BETWEEN 1 AND 4 AND length(NEW.code) <> NEW.level)
       OR (NEW.level = 5 AND (length(NEW.code) < 5 OR length(NEW.code) > 8)) THEN
        RAISE EXCEPTION 'account_plan: nivel/longitud inconsistentes (code=%, level=%)', NEW.code, NEW.level;
    END IF;

    IF NEW.parent_id IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM account_plan
                       WHERE id = NEW.parent_id
                         AND tenant_id = NEW.tenant_id
                         AND level = NEW.level - 1
                         AND is_active = TRUE) THEN
            RAISE EXCEPTION 'account_plan: padre inválido o de otra empresa (parent=%, level=%)', NEW.parent_id, NEW.level;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM account_plan p
                       WHERE p.id = NEW.parent_id AND NEW.code LIKE p.code || '%') THEN
            RAISE EXCEPTION 'account_plan: el código hija no hereda el prefijo del padre (%)', NEW.code;
        END IF;
    ELSIF NEW.level <> 1 THEN
        RAISE EXCEPTION 'account_plan: cuenta de nivel % sin padre', NEW.level;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_account_plan_structure ON account_plan;
CREATE TRIGGER trg_account_plan_structure
    BEFORE INSERT OR UPDATE ON account_plan
    FOR EACH ROW EXECUTE FUNCTION chk_account_plan_structure();

-- §5.b Mantenimiento automático de is_selectable
CREATE OR REPLACE FUNCTION sync_account_plan_selectable() RETURNS trigger AS $$
DECLARE
    v_new_parent BOOLEAN;
BEGIN
    IF NEW.parent_id IS NOT NULL THEN
        UPDATE account_plan
           SET is_selectable = FALSE, updated_at = now()
         WHERE id = NEW.parent_id AND tenant_id = NEW.tenant_id;
    END IF;
    IF (TG_OP = 'INSERT') THEN
        UPDATE account_plan
           SET is_selectable = (NEW.level >= 4)
         WHERE id = NEW.id AND tenant_id = NEW.tenant_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_account_plan_selectable ON account_plan;
CREATE TRIGGER trg_account_plan_selectable
    AFTER INSERT OR UPDATE OF parent_id ON account_plan
    FOR EACH ROW EXECUTE FUNCTION sync_account_plan_selectable();

-- §5.c Protección de cuentas con movimiento (constitución II)
CREATE OR REPLACE FUNCTION chk_account_plan_protected() RETURNS trigger AS $$
DECLARE
    v_used INT;
BEGIN
    SELECT count(*) INTO v_used
      FROM journal_entry_line l
     WHERE l.account_id = OLD.id AND l.empresa_id = OLD.tenant_id;

    IF TG_OP = 'DELETE' THEN
        IF v_used > 0 OR EXISTS (SELECT 1 FROM account_plan c
                                  WHERE c.parent_id = OLD.id
                                    AND c.tenant_id = OLD.tenant_id) THEN
            RAISE EXCEPTION 'account_plan: no se puede eliminar la cuenta (tiene imputaciones o hijas)';
        END IF;
        RETURN OLD;
    END IF;

    IF TG_OP = 'UPDATE' AND (OLD.is_active = TRUE AND NEW.is_active = FALSE) AND v_used > 0 THEN
        RAISE EXCEPTION 'account_plan: no se puede desactivar una cuenta con asientos asociados';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_account_plan_protected ON account_plan;
CREATE TRIGGER trg_account_plan_protected
    BEFORE UPDATE OR DELETE ON account_plan
    FOR EACH ROW EXECUTE FUNCTION chk_account_plan_protected();
