-- ============================================================
--  003_journal.sql
--  Diario contable (SPEC-002): journal_entry / journal_entry_line,
--  FK compuesta multi-tenant e inmutabilidad de POSTED/CANCELLED
--  (constitución II). Idempotente.
--  Alineado con backend/src/models/acct/journal.py.
-- ============================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_entry_tipo') THEN
        CREATE TYPE journal_entry_tipo AS ENUM (
            'GENERAL', 'COBRO', 'PRONTO_PAGO', 'REVERSAL', 'ADJUSTMENT'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_entry_estado') THEN
        CREATE TYPE journal_entry_estado AS ENUM ('DRAFT', 'POSTED', 'CANCELLED');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS journal_entry (
    id             UUID                  PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id     BIGINT                NOT NULL,
    ejercicio      INTEGER               NOT NULL,
    fecha          DATE                  NOT NULL,
    tipo           journal_entry_tipo    NOT NULL,
    concepto       VARCHAR(255)          NOT NULL,
    numero_asiento BIGINT                NULL,
    original_id    UUID                  NULL,
    created_by     VARCHAR(120)          NULL,
    estado         journal_entry_estado  NOT NULL DEFAULT 'POSTED',
    created_at     TIMESTAMPTZ           NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_journal_entry_empresa_id
    ON journal_entry (empresa_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_journal_entry_tenant_id
    ON journal_entry (empresa_id, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_journal_entry_tenant_numero
    ON journal_entry (empresa_id, ejercicio, numero_asiento);

CREATE TABLE IF NOT EXISTS journal_entry_line (
    id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id       BIGINT        NOT NULL,
    journal_entry_id UUID          NOT NULL,
    account_id       BIGINT        NULL,
    line_no          INTEGER       NULL,
    cuenta           VARCHAR(16)   NOT NULL,
    debe             NUMERIC(18,4) NOT NULL DEFAULT 0,
    haber            NUMERIC(18,4) NOT NULL DEFAULT 0,
    descripcion      VARCHAR(255)  NULL,
    CONSTRAINT fk_journal_line_empresa_entry
        FOREIGN KEY (empresa_id, journal_entry_id)
        REFERENCES journal_entry (empresa_id, id),
    CONSTRAINT debe_non_negative CHECK (debe >= 0),
    CONSTRAINT haber_non_negative CHECK (haber >= 0),
    CONSTRAINT line_debit_xor_credit CHECK (
        (debe > 0 AND haber = 0) OR (debe = 0 AND haber > 0)
    )
);

CREATE INDEX IF NOT EXISTS ix_journal_entry_line_empresa_id
    ON journal_entry_line (empresa_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_journal_entry_line_empresa_id
    ON journal_entry_line (empresa_id, id);

-- Contador correlativo por (empresa, ejercicio) (SPEC-002 T008). Row-locked
-- con SELECT ... FOR UPDATE dentro de la transacción del asentado.
CREATE TABLE IF NOT EXISTS journal_sequence (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id     BIGINT   NOT NULL,
    ejercicio      INTEGER  NOT NULL,
    ultimo_numero  BIGINT   NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_journal_sequence_empresa_id
    ON journal_sequence (empresa_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_journal_sequence_pair
    ON journal_sequence (empresa_id, ejercicio);

-- Inmutabilidad del diario: POSTED/CANCELLED no admiten UPDATE ni DELETE.
-- Única mutación permitida: la transición POSTED -> CANCELLED del original
-- cuando se crea un asiento REVERSAL enlazado (SPEC-002 US3). Cualquier otra
-- UPDATE o cualquier DELETE se deniega.
CREATE OR REPLACE FUNCTION chk_journal_entry_immutable_posted() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.estado = 'POSTED' AND NEW.estado = 'CANCELLED' THEN
        RETURN NEW;
    END IF;
    IF OLD.estado IN ('POSTED', 'CANCELLED') THEN
        RAISE EXCEPTION 'journal_entry: asiento % inmutable (operación % denegada)', OLD.estado, TG_OP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_journal_entry_immutable ON journal_entry;
CREATE TRIGGER trg_journal_entry_immutable
    BEFORE UPDATE OR DELETE ON journal_entry
    FOR EACH ROW EXECUTE FUNCTION chk_journal_entry_immutable_posted();

-- Las líneas de un asiento POSTED/CANCELLED tampoco se mutan
CREATE OR REPLACE FUNCTION chk_journal_entry_line_immutable() RETURNS trigger AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM journal_entry e
        WHERE e.id = OLD.journal_entry_id
          AND e.estado IN ('POSTED', 'CANCELLED')
    ) THEN
        RAISE EXCEPTION 'journal_entry_line: línea de asiento POSTED/CANCELLED inmutable (operación % denegada)', TG_OP;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_journal_entry_line_immutable ON journal_entry_line;
CREATE TRIGGER trg_journal_entry_line_immutable
    BEFORE UPDATE OR DELETE ON journal_entry_line
    FOR EACH ROW EXECUTE FUNCTION chk_journal_entry_line_immutable();

-- §5.d Solo cuentas apuntables y activas de la misma empresa reciben apuntes
CREATE OR REPLACE FUNCTION chk_journal_line_account_selectable() RETURNS trigger AS $$
DECLARE
    v_bad INT;
BEGIN
    IF NEW.account_id IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT count(*) INTO v_bad
      FROM account_plan a
     WHERE a.id = NEW.account_id
       AND a.tenant_id = NEW.empresa_id
       AND a.is_selectable = TRUE
       AND a.is_active = TRUE;

    IF v_bad = 0 THEN
        RAISE EXCEPTION
          'journal_entry_line: la cuenta % no es apuntable o no pertenece a la empresa (empresa %)',
          NEW.account_id, NEW.empresa_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_journal_line_account_selectable ON journal_entry_line;
CREATE TRIGGER trg_journal_line_account_selectable
    BEFORE INSERT OR UPDATE OF account_id ON journal_entry_line
    FOR EACH ROW EXECUTE FUNCTION chk_journal_line_account_selectable();

-- Partida doble estricta: se valida al finalizar la transacción para permitir
-- insertar la cabecera y sus líneas en operaciones separadas.
CREATE OR REPLACE FUNCTION chk_journal_entry_balance() RETURNS trigger AS $$
DECLARE
    v_entry_id UUID;
    v_empresa_id BIGINT;
    v_debe NUMERIC(18,4);
    v_haber NUMERIC(18,4);
    v_lineas_debe INTEGER;
    v_lineas_haber INTEGER;
BEGIN
    IF TG_TABLE_NAME = 'journal_entry' THEN
        IF TG_OP = 'DELETE' THEN
            v_entry_id := OLD.id;
            v_empresa_id := OLD.empresa_id;
        ELSE
            v_entry_id := NEW.id;
            v_empresa_id := NEW.empresa_id;
        END IF;
    ELSE
        IF TG_OP = 'DELETE' THEN
            v_entry_id := OLD.journal_entry_id;
            v_empresa_id := OLD.empresa_id;
        ELSE
            v_entry_id := NEW.journal_entry_id;
            v_empresa_id := NEW.empresa_id;
        END IF;
    END IF;

    SELECT
        COALESCE(SUM(debe), 0),
        COALESCE(SUM(haber), 0),
        COUNT(*) FILTER (WHERE debe > 0),
        COUNT(*) FILTER (WHERE haber > 0)
    INTO v_debe, v_haber, v_lineas_debe, v_lineas_haber
    FROM journal_entry_line
    WHERE empresa_id = v_empresa_id AND journal_entry_id = v_entry_id;

    IF v_lineas_debe = 0 OR v_lineas_haber = 0 OR v_debe <> v_haber THEN
        RAISE EXCEPTION
            'journal_entry: asiento % desbalanceado (Debe %, Haber %)',
            v_entry_id, v_debe, v_haber;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_journal_entry_balance ON journal_entry;
CREATE CONSTRAINT TRIGGER trg_journal_entry_balance
    AFTER INSERT OR UPDATE OR DELETE ON journal_entry
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION chk_journal_entry_balance();

DROP TRIGGER IF EXISTS trg_journal_entry_line_balance ON journal_entry_line;
CREATE CONSTRAINT TRIGGER trg_journal_entry_line_balance
    AFTER INSERT OR UPDATE OR DELETE ON journal_entry_line
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION chk_journal_entry_balance();
