-- ============================================================
--  004_iam.sql
--  Identidad y multiempresa (SPEC-003): companies, users, user_companies,
--  índices y empresa por defecto única por usuario. Idempotente.
--  Alineado con backend/src/models/iam/*.py.
--
--  `companies` es el ancla de tenancy referenciada por account_plan
--  (001_account_plan.sql); por eso el runner aplica 004 antes que 001.
-- ============================================================

CREATE TABLE IF NOT EXISTS companies (
    company_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nif          VARCHAR(20)  NOT NULL,
    razon_social VARCHAR(200) NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(200) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_company_rol') THEN
        CREATE TYPE user_company_rol AS ENUM ('ADMIN', 'ACCOUNTANT', 'READ_ONLY');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS user_companies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT           NOT NULL,
    company_id BIGINT           NOT NULL,
    role       user_company_rol NOT NULL,
    is_default BOOLEAN          NOT NULL DEFAULT FALSE,
    is_active  BOOLEAN          NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_companies_pair UNIQUE (user_id, company_id),
    CONSTRAINT fk_user_companies_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_companies_company
        FOREIGN KEY (company_id) REFERENCES companies (company_id)
);

CREATE INDEX IF NOT EXISTS ix_user_companies_user_id
    ON user_companies (user_id);
CREATE INDEX IF NOT EXISTS ix_user_companies_company_id
    ON user_companies (company_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_companies_default_one
    ON user_companies (user_id) WHERE is_default = TRUE;
