-- ============================================================
--  005_fiscal_invoice.sql
--  Ejercicios y facturas (SPEC-004): fiscal_year e invoice multi-tenant.
--  Idempotente.
--
--  Nota de alineación: SPEC-004 data-model.md describe los FK a
--  `journal_entry` como BIGINT, pero el diario implementado
--  (backend/src/models/acct/journal.py) usa PK UUID. Esta migración usa
--  UUID y FK compuesta (empresa_id, id) para preservar el multi-tenancy.
--  Los modelos `fiscal_year`/`invoice` aún no existen (SPEC-004 sin
--  implementar); esta migración los deja preparados a nivel de esquema.
--
--  Dependencia: journal_entry (003_journal.sql).
-- ============================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invoice_tipo') THEN
        CREATE TYPE invoice_tipo AS ENUM ('emitida', 'recibida');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS fiscal_year (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id              BIGINT      NOT NULL,
    year                    INTEGER     NOT NULL,
    date_start              DATE        NOT NULL,
    date_end                DATE        NOT NULL,
    is_closed               BOOLEAN     NOT NULL DEFAULT FALSE,
    closed_at               TIMESTAMPTZ NULL,
    regularizacion_entry_id UUID        NULL,
    cierre_entry_id         UUID        NULL,
    created_by              VARCHAR(120) NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fiscal_year_empresa_year UNIQUE (empresa_id, year),
    CONSTRAINT chk_fiscal_year_rango CHECK (date_end >= date_start),
    CONSTRAINT fk_fiscal_year_regularizacion
        FOREIGN KEY (empresa_id, regularizacion_entry_id)
        REFERENCES journal_entry (empresa_id, id),
    CONSTRAINT fk_fiscal_year_cierre
        FOREIGN KEY (empresa_id, cierre_entry_id)
        REFERENCES journal_entry (empresa_id, id)
);

CREATE INDEX IF NOT EXISTS ix_fiscal_year_empresa_id
    ON fiscal_year (empresa_id);

CREATE TABLE IF NOT EXISTS invoice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  BIGINT        NOT NULL,
    tipo        invoice_tipo  NOT NULL,
    ejercicio   INTEGER       NOT NULL,
    numero_seq  BIGINT        NOT NULL,
    nif_tercero VARCHAR(20)   NOT NULL,
    fecha       DATE          NOT NULL,
    base        NUMERIC(18,4) NOT NULL DEFAULT 0,
    cuota_iva   NUMERIC(18,4) NOT NULL DEFAULT 0,
    total       NUMERIC(18,4) NOT NULL DEFAULT 0,
    asiento_id  UUID          NULL,
    created_by  VARCHAR(120)  NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_invoice_empresa_ejercicio_numero
        UNIQUE (empresa_id, ejercicio, numero_seq),
    CONSTRAINT chk_invoice_total CHECK (total = base + cuota_iva),
    CONSTRAINT chk_invoice_base_non_negative CHECK (base >= 0),
    CONSTRAINT fk_invoice_asiento
        FOREIGN KEY (empresa_id, asiento_id)
        REFERENCES journal_entry (empresa_id, id)
);

CREATE INDEX IF NOT EXISTS ix_invoice_empresa_id
    ON invoice (empresa_id);
